name: XCatch
version: '${project.version}'
main: io.github.dediamondpro.xcatch.XCatch
api-version: 1.13
authors: [ DeDiamondPro ]
description: A simple, efficient plugin to catch x-rayers.
commands:
  xcatch:
    description: XCatch base command
permissions:
  xcatch.*:
    description: Gives you all of the XCatch permissions.
    default: op
    children:
      xcatch.alert: true
      xcatch.bypass: true
      xcatch.noban: true
      xcatch.command: true
  xcatch.alert:
    default: op
    description: Gives you the permission to see XCatch alerts.
  xcatch.bypass:
    default: false
    description: Players with this permission bypass all XCatch checks.
  xcatch.noban:
    default: false
    description: XCatch will flag players with this permission as normal, but it won't ban them.
  xcatch.command:
    default: op
    description: Give players with this permission access to the XCatch command.